import { Category, NewsArticle } from "./types";

export const categories: Category[] = [
  { id: "c1", name: "महाराष्ट्र", slug: "maharashtra" },
  { id: "c2", name: "राजकारण", slug: "politics" },
  { id: "c3", name: "गुन्हेगारी", slug: "crime" },
  { id: "c4", name: "शेती", slug: "agriculture" },
  { id: "c5", name: "शिक्षण", slug: "education" },
  { id: "c6", name: "व्यापार", slug: "business" },
  { id: "c7", name: "तंत्रज्ञान", slug: "technology" },
  { id: "c8", name: "मनोरंजन", slug: "entertainment" },
  { id: "c9", name: "क्रीडा", slug: "sports" },
  { id: "c10", name: "हवामान", slug: "weather" },
];

export const mockArticles: NewsArticle[] = [
  {
    id: "Qx2jdRiRRoHo6traosDt",
    title: "NEET UG CAP Round-1: महाराष्ट्रातील MBBS आणि BDS प्रवेशाचे सुधारित वेळापत्रक जाहीर; २३ ऑगस्टला गुणवत्ता यादी",
    summary: "महाराष्ट्रातील वैद्यकीय आणि दंतवैद्यकीय (MBBS/BDS) पदवी प्रवेशासाठी राबवल्या जाणाऱ्या 'NEET UG CAP Round-1' च्या वेळापत्रकात राज्य सामाईक प्रवेश परीक्षा कक्षाने (State CET Cell) महत्त्वपूर्ण बदल केले आहेत.",
    content: `<p><strong>मुंबई:</strong> महाराष्ट्रातील वैद्यकीय आणि दंतवैद्यकीय (MBBS/BDS) पदवी प्रवेशासाठी राबवल्या जाणाऱ्या 'NEET UG CAP Round-1' च्या वेळापत्रकात राज्य सामाईक प्रवेश परीक्षा कक्षाने (State CET Cell) महत्त्वपूर्ण बदल केले आहेत.</p><p>नव्या वेळापत्रकानुसार सुधारित तात्पुरती गुणवत्ता यादी २३ ऑगस्ट रोजी प्रसिद्ध होणार असून, महाविद्यालयांचे पसंतीक्रम भरण्याची प्रक्रिया २६ ऑगस्टपासून सुरू होणार आहे. लाखो वैद्यकीय विद्यार्थ्यांचे लक्ष या प्रवेश प्रक्रियेकडे लागले आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[4],
    location: { state: "महाराष्ट्र", district: "मुंबई" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    lastUpdated: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    author: "राज्यवाणी शिक्षण प्रतिनिधी",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    tags: ["NEET UG", "महाराष्ट्र प्रवेश प्रक्रिया", "MBBS प्रवेश", "BDS प्रवेश", "CET Cell"],
    isBreaking: true,
    aiGenerated: false,
    views: 18420,
  },
  {
    id: "news-weather-1",
    title: "महाराष्ट्रात मान्सून पुन्हा सक्रिय: पुढील ७२ तास कोकण, पश्चिम महाराष्ट्र आणि विदर्भासाठी हायअलर्ट",
    summary: "बंगालच्या उपसागरात निर्माण झालेल्या कमी दाबाच्या क्षेत्रामुळे महाराष्ट्रात मान्सूनचा जोर पुन्हा वाढला असून हवामान खात्याने कोकण, मध्य महाराष्ट्र आणि विदर्भासाठी अलर्ट जारी केला आहे.",
    content: `<p><strong>मुंबई/पुणे:</strong> राज्यातील बहुतांश जिल्ह्यांमध्ये पावसाने दमदार पुनरागमन केले असून भारतीय हवामान विभागाने (IMD) पुढील ७२ तासांसाठी अतिमुसळधार ते मुसळधार पावसाचा इशारा दिला आहे. कोकणातील रायगड, रत्नागिरी, सिंधुदुर्ग तसेच पश्चिम महाराष्ट्रातील पुणे व सातारा जिल्ह्यांच्या घाटमाथ्यावर मुसळधार पावसाची शक्यता वर्तवण्यात आली आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[9],
    location: { state: "महाराष्ट्र" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    lastUpdated: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    author: "अनिकेत देशमुख (ज्येष्ठ संपादक)",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    tags: ["हवामान", "पाऊस", "रेड अलर्ट", "महाराष्ट्र", "आपत्ती व्यवस्थापन"],
    isBreaking: false,
    aiGenerated: true,
    views: 15420,
  },
  {
    id: "news-2",
    title: "शेतकऱ्यांसाठी मोठी दिलासादायक बातमी: खरीप पीक विम्याचे अग्रिम २५% वाटप थेट बँक खात्यात सुरू",
    summary: "राज्य शासनाने राज्यातील दुष्काळग्रस्त व अतिवृष्टीग्रस्त शेतकऱ्यांसाठी पीक विमा योजनेअंतर्गत अग्रिम २५ टक्के भरपाई देण्याचे आदेश दिले असून थेट डीबीटी प्रणालीद्वारे वाटप सुरू झाले आहे.",
    content: `<p><strong>मुंबई/छत्रपती संभाजीनगर:</strong> राज्यातील लाखो शेतकरी बांधवांसाठी राज्य सरकारकडून अत्यंत दिलासादायक बातमी समोर आली आहे. खरीप पिकांसाठी 'प्रधानमंत्री पीक विमा योजना' व 'एक रुपयात पीक विमा' योजनेअंतर्गत अग्रिम २५ टक्के भरपाई थेट शेतकऱ्यांच्या खात्यात जमा होत आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[3],
    location: { state: "महाराष्ट्र" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    lastUpdated: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    author: "स्मिता पाटील (कृषी प्रतिनिधी)",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    tags: ["शेती", "पीक विमा", "महाराष्ट्र शासन", "शेतकरी", "डीबीटी"],
    isBreaking: true,
    aiGenerated: true,
    views: 8900,
  },
  {
    id: "news-3",
    title: "पुणे मेट्रोच्या भुयारी व उन्नत मार्गिकेचा ऐतिहासिक विस्तार; स्वारगेट प्रवास आता फक्त ३० मिनिटांत",
    summary: "पुणे शहरातील वाहतूक कोंडीवर मात करण्यासाठी मेट्रोच्या नवीन भूमिगत आणि उन्नत मार्गिकेचे लोकार्पण करण्यात आले.",
    content: `<p><strong>पुणे:</strong> पुणे शहरातील वाहतूक कोंडी सोडवण्याच्या दिशेने मेट्रोच्या भुयारी विस्तारित मार्गिकेचे लोकार्पण करण्यात आले. यामुळे शिवाजीनगर ते स्वारगेट हा प्रवास आता अवघ्या २५ ते ३० मिनिटांत पूर्ण होणार आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[0],
    location: { state: "महाराष्ट्र", district: "पुणे" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    lastUpdated: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    author: "अनिकेत देशमुख",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    tags: ["पुणे मेट्रो", "पुणे", "वाहतूक", "इन्फ्रास्ट्रक्चर"],
    isBreaking: false,
    aiGenerated: true,
    views: 12300,
  },
  {
    id: "news-4",
    title: "विधानसभा निवडणुकीपूर्वी महायुती आणि महाविकास आघाडीत जागावाटपाच्या बैठकांचा धडाका",
    summary: "आगामी महाराष्ट्र विधानसभा निवडणुकीच्या पार्श्वभूमीवर राजकीय हालचालींना वेग आला असून प्रमुख आघाड्यांमध्ये जागावाटपाची अंतिम चर्चा सुरू आहे.",
    content: `<p><strong>मुंबई:</strong> आगामी विधानसभा निवडणुकीच्या पार्श्वभूमीवर मुंबईत राजकीय हालचालींना वेग आला आहे. जागावाटपाचे सूत्र निश्चित करण्यासाठी दोन्ही बाजूंनी महत्त्वाच्या बैठकांचे सत्र सुरू आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[1],
    location: { state: "महाराष्ट्र", district: "मुंबई" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    lastUpdated: null,
    author: "रोहित जोशी (राजकीय विश्लेषक)",
    tags: ["महाराष्ट्र राजकारण", "विधानसभा निवडणूक", "महायुती", "महाविकास आघाडी"],
    isBreaking: true,
    aiGenerated: true,
    views: 24500,
  },
  {
    id: "news-5",
    title: "भारतीय रिझर्व्ह बँकेचा रेपो दर जैसे थे; गृहकर्जाचे हप्ते स्थिर राहणार",
    summary: "आरबीआयच्या पतधोरण समितीने (MPC) रेपो दरात कोणताही बदल न करण्याचा निर्णय घेतला असून महागाई नियंत्रणात ठेवण्यावर भर दिला आहे.",
    content: `<p><strong>मुंबई:</strong> भारतीय रिझर्व्ह बँकेचे गव्हर्नर यांच्या अध्यक्षतेखाली झालेल्या बैठकीत रेपो दर ६.५ टक्क्यांवर कायम ठेवण्याचा निर्णय घेण्यात आला आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[5],
    location: { state: "राष्ट्रीय" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    lastUpdated: null,
    author: "आदित्य शर्मा (अर्थ प्रतिनिधी)",
    tags: ["RBI", "रेपो दर", "गृहकर्ज", "अर्थव्यवस्था"],
    isBreaking: false,
    aiGenerated: true,
    views: 11200,
  },
  {
    id: "news-6",
    title: "छत्रपती संभाजीनगरमध्ये सायबर गुन्हेगारांवर पोलिसांची मोठी कारवाई; ३ कोटींची फसवणूक उघड",
    summary: "शेअर मार्केटमध्ये भरघोस नफ्याचे आमिष दाखवून नागरिकांची फसवणूक करणाऱ्या टोळीचा सायबर पोलिसांनी पर्दाफाश केला.",
    content: `<p><strong>छत्रपती संभाजीनगर:</strong> सायबर पोलिसांनी केलेल्या धडक कारवाईत आंतरराज्यीय टोळीच्या ५ सदस्यांना गजाआड करण्यात आले असून ३ कोटी रुपयांहून अधिक रकमेची फसवणूक उघडकीस आली आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[2],
    location: { state: "महाराष्ट्र", district: "छत्रपती संभाजीनगर" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    lastUpdated: null,
    author: "विशेष क्राईम प्रतिनिधी",
    tags: ["सायबर गुन्हे", "छत्रपती संभाजीनगर", "पोलीस कारवाई"],
    isBreaking: false,
    aiGenerated: true,
    views: 7600,
  },
  {
    id: "news-7",
    title: "भारतीय क्रिकेट संघाचे इंग्लंड दौऱ्यासाठी जोरदार सराव सत्र; कर्णधाराचे विजयाचा विश्वास",
    summary: "आगामी कसोटी मालिकेसाठी भारतीय क्रिकेट खेळाडूंनी मैदानावर घाम गाळण्यास सुरुवात केली आहे.",
    content: `<p><strong>लंडन:</strong> भारतीय क्रिकेट संघाने आगामी महत्त्वाच्या मालिकेसाठी सराव सुरू केला आहे. युवा खेळाडूंच्या कामगिरीवर सर्वांचे लक्ष लागून राहिले आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[8],
    location: { state: "राष्ट्रीय" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    lastUpdated: null,
    author: "क्रीडा डेस्क",
    tags: ["क्रिकेट", "टीम इंडिया", "कसोटी"],
    isBreaking: false,
    aiGenerated: true,
    views: 19800,
  }
];
