import { Category, NewsArticle } from "./types";

export const categories: Category[] = [
  { id: "c1", name: "महाराष्ट्र", slug: "maharashtra" },
  { id: "c2", name: "राजकारण", slug: "politics" },
  { id: "c3", name: "गुन्हेगारी", slug: "crime" },
  { id: "c4", name: "शेती", slug: "agriculture" },
  { id: "c5", name: "शिक्षण", slug: "education" },
  { id: "c6", name: "व्यापार", slug: "business" },
  { id: "c7", name: "तंत्रज्ञान", slug: "technology" },
  { id: "c8", name: "मनोरंजन", slug: "entertainment" },
  { id: "c9", name: "क्रीडा", slug: "sports" },
  { id: "c10", name: "हवामान", slug: "weather" },
  { id: "c11", name: "आरोग्य", slug: "health" },
  { id: "c12", name: "राष्ट्रीय", slug: "national" },
];

export const mockArticles: NewsArticle[] = [
  {
    id: "Qx2jdRiRRoHo6traosDt",
    title: "NEET UG CAP Round-1: महाराष्ट्रातील MBBS आणि BDS प्रवेशाचे सुधारित वेळापत्रक जाहीर; २३ ऑगस्टला गुणवत्ता यादी",
    summary: "महाराष्ट्रातील वैद्यकीय आणि दंतवैद्यकीय (MBBS/BDS) पदवी प्रवेशासाठी राबवल्या जाणाऱ्या 'NEET UG CAP Round-1' च्या वेळापत्रकात राज्य सामाईक प्रवेश परीक्षा कक्षाने (State CET Cell) महत्त्वपूर्ण बदल केले आहेत.",
    content: `<p><strong>मुंबई:</strong> महाराष्ट्रातील वैद्यकीय आणि दंतवैद्यकीय (MBBS/BDS) पदवी प्रवेशासाठी राबवल्या जाणाऱ्या 'NEET UG CAP Round-1' च्या वेळापत्रकात राज्य सामाईक प्रवेश परीक्षा कक्षाने (State CET Cell) महत्त्वपूर्ण बदल केले आहेत.</p><p>नव्या वेळापत्रकानुसार सुधारित तात्पुरती गुणवत्ता यादी २३ ऑगस्ट रोजी प्रसिद्ध होणार असून, महाविद्यालयांचे पसंतीक्रम भरण्याची प्रक्रिया २६ ऑगस्टपासून सुरू होणार आहे. लाखो वैद्यकीय विद्यार्थ्यांचे लक्ष या प्रवेश प्रक्रियेकडे लागले आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format%2Ccompress&fm=webp&fit=crop&q=38&w=480",
    category: categories[4],
    location: { state: "महाराष्ट्र", district: "मुंबई" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    lastUpdated: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    author: "राज्यवाणी शिक्षण प्रतिनिधी",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    tags: ["NEET UG", "महाराष्ट्र प्रवेश प्रक्रिया", "MBBS प्रवेश", "BDS प्रवेश", "CET Cell", "शिक्षण"],
    isBreaking: true,
    aiGenerated: false,
    views: 18420,
  },
  {
    id: "news-weather-1",
    title: "महाराष्ट्रात मान्सून पुन्हा सक्रिय: पुढील ७२ तास कोकण, पश्चिम महाराष्ट्र आणि विदर्भासाठी हायअलर्ट",
    summary: "बंगालच्या उपसागरात निर्माण झालेल्या कमी दाबाच्या क्षेत्रामुळे महाराष्ट्रात मान्सूनचा जोर पुन्हा वाढला असून हवामान खात्याने कोकण, मध्य महाराष्ट्र आणि विदर्भासाठी अलर्ट जारी केला आहे.",
    content: `<p><strong>मुंबई/पुणे:</strong> राज्यातील बहुतांश जिल्ह्यांमध्ये पावसाने दमदार पुनरागमन केले असून भारतीय हवामान विभागाने (IMD) पुढील ७२ तासांसाठी अतिमुसळधार ते मुसळधार पावसाचा इशारा दिला आहे. कोकणातील रायगड, रत्नागिरी, सिंधुदुर्ग तसेच पश्चिम महाराष्ट्रातील पुणे व सातारा जिल्ह्यांच्या घाटमाथ्यावर मुसळधार पावसाची शक्यता वर्तवण्यात आली आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[9],
    location: { state: "महाराष्ट्र", district: "पुणे" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    lastUpdated: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    author: "अनिकेत देशमुख (ज्येष्ठ संपादक)",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    tags: ["हवामान", "पाऊस", "रेड अलर्ट", "महाराष्ट्र", "विदर्भ", "कोकण", "आपत्ती व्यवस्थापन"],
    isBreaking: false,
    aiGenerated: true,
    views: 15420,
  },
  {
    id: "news-2",
    title: "शेतकऱ्यांसाठी मोठी दिलासादायक बातमी: खरीप पीक विम्याचे अग्रिम २५% वाटप थेट बँक खात्यात सुरू",
    summary: "राज्य शासनाने राज्यातील दुष्काळग्रस्त व अतिवृष्टीग्रस्त शेतकऱ्यांसाठी पीक विमा योजनेअंतर्गत अग्रिम २५ टक्के भरपाई देण्याचे आदेश दिले असून थेट डीबीटी प्रणालीद्वारे वाटप सुरू झाले आहे.",
    content: `<p><strong>मुंबई/छत्रपती संभाजीनगर:</strong> राज्यातील लाखो शेतकरी बांधवांसाठी राज्य सरकारकडून अत्यंत दिलासादायक बातमी समोर आली आहे. खरीप पिकांसाठी 'प्रधानमंत्री पीक विमा योजना' व 'एक रुपयात पीक विमा' योजनेअंतर्गत अग्रिम २५ टक्के भरपाई थेट शेतकऱ्यांच्या खात्यात जमा होत आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[3],
    location: { state: "महाराष्ट्र", district: "छत्रपती संभाजीनगर" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    lastUpdated: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    author: "स्मिता पाटील (कृषी प्रतिनिधी)",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    tags: ["शेती", "पीक विमा", "महाराष्ट्र शासन", "शेतकरी", "डीबीटी", "मराठवाडा"],
    isBreaking: true,
    aiGenerated: true,
    views: 8900,
  },
  {
    id: "news-3",
    title: "पुणे मेट्रोच्या भुयारी व उन्नत मार्गिकेचा ऐतिहासिक विस्तार; स्वारगेट प्रवास आता फक्त ३० मिनिटांत",
    summary: "पुणे शहरातील वाहतूक कोंडीवर मात करण्यासाठी मेट्रोच्या नवीन भूमिगत आणि उन्नत मार्गिकेचे लोकार्पण करण्यात आले.",
    content: `<p><strong>पुणे:</strong> पुणे शहरातील वाहतूक कोंडी सोडवण्याच्या दिशेने मेट्रोच्या भुयारी विस्तारित मार्गिकेचे लोकार्पण करण्यात आले. यामुळे शिवाजीनगर ते स्वारगेट हा प्रवास आता अवघ्या २५ ते ३० मिनिटांत पूर्ण होणार आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[0],
    location: { state: "महाराष्ट्र", district: "पुणे" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    lastUpdated: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    author: "अनिकेत देशमुख",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    tags: ["पुणे मेट्रो", "पुणे", "वाहतूक", "इन्फ्रास्ट्रक्चर", "पश्चिम महाराष्ट्र"],
    isBreaking: false,
    aiGenerated: true,
    views: 12300,
  },
  {
    id: "news-4",
    title: "विधानसभा निवडणुकीपूर्वी महायुती आणि महाविकास आघाडीत जागावाटपाच्या बैठकांचा धडाका",
    summary: "आगामी महाराष्ट्र विधानसभा निवडणुकीच्या पार्श्वभूमीवर राजकीय हालचालींना वेग आला असून प्रमुख आघाड्यांमध्ये जागावाटपाची अंतिम चर्चा सुरू आहे.",
    content: `<p><strong>मुंबई:</strong> आगामी विधानसभा निवडणुकीच्या पार्श्वभूमीवर मुंबईत राजकीय हालचालींना वेग आला आहे. जागावाटपाचे सूत्र निश्चित करण्यासाठी दोन्ही बाजूंनी महत्त्वाच्या बैठकांचे सत्र सुरू आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[1],
    location: { state: "महाराष्ट्र", district: "मुंबई" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    lastUpdated: null,
    author: "रोहित जोशी (राजकीय विश्लेषक)",
    tags: ["महाराष्ट्र राजकारण", "विधानसभा निवडणूक", "महायुती", "महाविकास आघाडी", "राजकारण"],
    isBreaking: true,
    aiGenerated: true,
    views: 24500,
  },
  {
    id: "news-5",
    title: "भारतीय रिझर्व्ह बँकेचा रेपो दर जैसे थे; गृहकर्जाचे हप्ते स्थिर राहणार",
    summary: "आरबीआयच्या पतधोरण समितीने (MPC) रेपो दरात कोणताही बदल न करण्याचा निर्णय घेतला असून महागाई नियंत्रणात ठेवण्यावर भर दिला आहे.",
    content: `<p><strong>मुंबई:</strong> भारतीय रिझर्व्ह बँकेचे गव्हर्नर यांच्या अध्यक्षतेखाली झालेल्या बैठकीत रेपो दर ६.५ टक्क्यांवर कायम ठेवण्याचा निर्णय घेण्यात आला आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[5],
    location: { state: "महाराष्ट्र", district: "मुंबई" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    lastUpdated: null,
    author: "आदित्य शर्मा (अर्थ प्रतिनिधी)",
    tags: ["RBI", "रेपो दर", "गृहकर्ज", "अर्थव्यवस्था", "व्यापार"],
    isBreaking: false,
    aiGenerated: true,
    views: 11200,
  },
  {
    id: "news-6",
    title: "छत्रपती संभाजीनगरमध्ये सायबर गुन्हेगारांवर पोलिसांची मोठी कारवाई; ३ कोटींची फसवणूक उघड",
    summary: "शेअर मार्केटमध्ये भरघोस नफ्याचे आमिष दाखवून नागरिकांची फसवणूक करणाऱ्या टोळीचा सायबर पोलिसांनी पर्दाफाश केला.",
    content: `<p><strong>छत्रपती संभाजीनगर:</strong> सायबर पोलिसांनी केलेल्या धडक कारवाईत आंतरराज्यीय टोळीच्या ५ सदस्यांना गजाआड करण्यात आले असून ३ कोटी रुपयांहून अधिक रकमेची फसवणूक उघडकीस आली आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[2],
    location: { state: "महाराष्ट्र", district: "छत्रपती संभाजीनगर" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    lastUpdated: null,
    author: "विशेष क्राईम प्रतिनिधी",
    tags: ["सायबर गुन्हे", "छत्रपती संभाजीनगर", "पोलीस कारवाई", "गुन्हेगारी", "मराठवाडा"],
    isBreaking: false,
    aiGenerated: true,
    views: 7600,
  },
  {
    id: "news-7",
    title: "भारतीय क्रिकेट संघाचे इंग्लंड दौऱ्यासाठी जोरदार सराव सत्र; कर्णधाराचा विजयाचा विश्वास",
    summary: "आगामी कसोटी मालिकेसाठी भारतीय क्रिकेट खेळाडूंनी मैदानावर घाम गाळण्यास सुरुवात केली आहे.",
    content: `<p><strong>लंडन:</strong> भारतीय क्रिकेट संघाने आगामी महत्त्वाच्या मालिकेसाठी सराव सुरू केला आहे. युवा खेळाडूंच्या कामगिरीवर सर्वांचे लक्ष लागून राहिले आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[8],
    location: { state: "राष्ट्रीय" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    lastUpdated: null,
    author: "क्रीडा डेस्क",
    tags: ["क्रिकेट", "टीम इंडिया", "कसोटी", "क्रीडा"],
    isBreaking: false,
    aiGenerated: true,
    views: 19800,
  },
  {
    id: "news-8",
    title: "मराठी सिनेसृष्टीत नवा विक्रम: ऐतिहासिक चित्रपटाचा ट्रेलर यूट्यूबवर अवघ्या २४ तासांत नंबर १ ट्रेंडिंग",
    summary: "महाराष्ट्राच्या पराक्रमावर आधारित भव्य ऐतिहासिक मराठी चित्रपटाच्या टीझरने सर्व डिजिटल रेकॉर्ड मोडीत काढले असून प्रेक्षकांचा उत्स्फूर्त प्रतिसाद लाभत आहे.",
    content: `<p><strong>मुंबई:</strong> मराठी चित्रपटसृष्टीत ऐतिहासिक विषयांवरील चित्रपटांना प्रेक्षकांचा नेहमीच भरघोस पाठिंबा मिळतो. नव्या भव्य ऐतिहासिक चित्रपटाचा ट्रेलर प्रदर्शित होताच अवघ्या काही तासांत लाखो व्ह्यूज मिळवून ट्रेंडिंगमध्ये पहिल्या क्रमांकावर पोहोचला आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[7],
    location: { state: "महाराष्ट्र", district: "मुंबई" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    lastUpdated: null,
    author: "मनोरंजन ब्युरो",
    tags: ["मराठी सिनेमा", "चित्रपट", "मनोरंजन", "ट्रेलर"],
    isBreaking: false,
    aiGenerated: true,
    views: 16500,
  },
  {
    id: "news-9",
    title: "डिजिटल क्रांती: भारतीय भाषांसाठी अत्याधुनिक AI टूल सादर; मराठी भाषिकांना होणार थेट फायदा",
    summary: "भारतीय तंत्रज्ञान कंपन्यांनी स्थानिक भाषांमध्ये अचूक संभाषण आणि भाषांतर करणारी नवीन AI प्रणाली विकसित केली आहे.",
    content: `<p><strong>पुणे/बंगळुरू:</strong> देशातील तंत्रज्ञान क्षेत्राने कृत्रिम बुद्धिमत्ता (AI) क्षेत्रात मोठी झेप घेतली आहे. मराठीसह विविध भारतीय भाषांमध्ये अचूक मजकूर निर्मिती, व्हॉइस ट्रान्सलेशन आणि प्रशासकीय कामांसाठी हे टूल अत्यंत उपयुक्त ठरणार आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[6],
    location: { state: "महाराष्ट्र", district: "पुणे" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    lastUpdated: null,
    author: "टेक डेस्क",
    tags: ["तंत्रज्ञान", "AI", "डिजिटल भारत", "स्मार्टफोन"],
    isBreaking: false,
    aiGenerated: true,
    views: 14200,
  },
  {
    id: "news-10",
    title: "आरोग्य विशेष: पावसाळ्यात संसर्गजन्य आजारांपासून बचावासाठी तज्ज्ञांचे महत्त्वाचे मार्गदर्शन व टिप्स",
    summary: "बदलत्या हवामानात रोगप्रतिकारक शक्ती वाढवण्यासाठी आणि डेंग्यू-मलेरियासारख्या आजारांपासून दूर राहण्यासाठी आरोग्य विभागाने जाहीर केली मार्गदर्शक नियमावली.",
    content: `<p><strong>मुंबई:</strong> पावसाळ्याच्या मोसमात साथीच्या आजारांचा प्रादुर्भाव वाढू नये म्हणून आरोग्य विभागाने खबरदारीचे उपाय जाहीर केले आहेत. उकळलेले पाणी पिणे, घरगुती सकस आहार आणि वैयक्तिक स्वच्छता राखण्याचे आवाहन डॉक्टरांनी केले आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[10],
    location: { state: "महाराष्ट्र", district: "मुंबई" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
    lastUpdated: null,
    author: "डॉ. सुहास कुलकर्णी (आरोग्य सल्लागार)",
    tags: ["आरोग्य", "आरोग्य सल्ला", "फिटनेस", "पावसाळा काळजी"],
    isBreaking: false,
    aiGenerated: true,
    views: 13100,
  },
  {
    id: "news-11",
    title: "नागपूर-अमरावती औद्योगिक पट्ट्यात १०,००० कोटींची नवी गुंतवणूक; विदर्भात लाखो रोजगाराची संधी",
    summary: "विदर्भाच्या विकासाला गती देण्यासाठी राज्य सरकारने नवीन औद्योगिक धोरणांतर्गत मोठ्या प्रकल्पांना मंजुरी दिली आहे.",
    content: `<p><strong>नागपूर:</strong> विदर्भातील औद्योगिकीकरणाला गती देण्यासाठी नागपूर-अमरावती समृद्धी महामार्ग कॉरिडॉरवर नवीन मॅन्युफॅक्चरिंग हब उभारण्याचा निर्णय घेण्यात आला आहे. यामुळे विदर्भातील तरुणांना स्थानिक पातळीवर मोठ्या रोजगाराच्या संधी उपलब्ध होणार आहेत.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[5],
    location: { state: "महाराष्ट्र", district: "नागपूर" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    lastUpdated: null,
    author: "विदर्भ विशेष प्रतिनिधी",
    tags: ["विदर्भ", "नागपूर", "उद्योग", "रोजगार", "व्यापार"],
    isBreaking: true,
    aiGenerated: true,
    views: 18900,
  },
  {
    id: "news-12",
    title: "नाशिकच्या द्राक्ष व कांदा उत्पादक शेतकऱ्यांसाठी आधुनिक शीतगृहांचे जाळे; थेट निर्यातीला प्रोत्साहन",
    summary: "उत्तर महाराष्ट्रातील फळबागा आणि भाजीपाला उत्पादकांना जागतिक बाजारपेठ मिळवून देण्यासाठी विशेष कृषी निर्यात केंद्र सुरू करण्यात आले.",
    content: `<p><strong>नाशिक/जळगाव:</strong> उत्तर महाराष्ट्रातील शेतकरी बांधवांच्या उत्पादनाला आंतरराष्ट्रीय भाव मिळवून देण्यासाठी अत्याधुनिक कोल्ड स्टोरेज आणि पॅक हाऊस प्रकल्प कार्यान्वित करण्यात आला आहे.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[3],
    location: { state: "महाराष्ट्र", district: "नाशिक" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 11).toISOString(),
    lastUpdated: null,
    author: "उत्तर महाराष्ट्र कृषी प्रतिनिधी",
    tags: ["उत्तर महाराष्ट्र", "नाशिक", "द्राक्ष", "शेती", "शेतकरी"],
    isBreaking: false,
    aiGenerated: true,
    views: 11400,
  },
  {
    id: "news-13",
    title: "कोकण किनारपट्टी पर्यटन विकासासाठी १०० कोटींचा विशेष निधी मंजूर; सागरी किल्ले होणार अधिक सुसज्ज",
    summary: "सिंधुदुर्ग, रत्नागिरी आणि रायगडमधील ऐतिहासिक सागरी किल्ले आणि निसर्गरम्य समुद्रकिनाऱ्यांचे संवर्धन व पर्यटन सुविधांचा विस्तार होणार.",
    content: `<p><strong>रत्नागिरी/सिंधुदुर्ग:</strong> कोकणातील पर्यटनाला आंतरराष्ट्रीय स्तरावर नेण्यासाठी राज्य शासनाने विशेष निधीची तरतूद केली आहे. वॉटर स्पोर्ट्स आणि हेरिटेज वॉकसाठी आधुनिक सुविधा उपलब्ध केल्या जाणार आहेत.</p>`,
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format,compress&fm=webp&fit=crop&q=50&w=720",
    category: categories[0],
    location: { state: "महाराष्ट्र", district: "रत्नागिरी" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    lastUpdated: null,
    author: "कोकण प्रतिनिधी",
    tags: ["कोकण", "पर्यटन", "सिंधुदुर्ग", "रत्नागिरी", "महाराष्ट्र"],
    isBreaking: false,
    aiGenerated: true,
    views: 15600,
  }
];
